In [2]:
import numpy as np
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')

## Mod02 Lab

#### 使用 help() 函數查 range 的說明

In [ ]:
help(range)

#### 有一個 Tuple tup 如下，使用 "TAB" 鍵列出 tup 的所有 methods

In [ ]:
tup = (1,2,3,4)

In [ ]:
tup.

## Mod03 Lab

<b> 利用 arange() 建立一個 array([11, 14, 17, 20]) 的陣列 <b>

In [ ]:
np.arange(11,21,3)

<b>建立一個陣列如下，並列出陣列形狀與維度
```
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
```
</b>


In [3]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8]]
                ,[[9,10,11,12],[13,14,15,16]]
                ,[[17,18,19,20],[21,22,23,24]]])
print(ar3)
print('-'*50)
print(ar3.shape)
print('-'*50)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
--------------------------------------------------
(3, 2, 4)
--------------------------------------------------
3


## Mod04 Lab

<b>有一個 7x4 的陣列，每一列代表一個人的資料，人名放在 names 的陣列<br>
試著取得 Will 的資料如下<br>
```
array([[ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843]])
```
</b>

In [4]:
# every row of data corresponding to index of names
np.random.seed(20)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [5]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
data

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644]])

In [7]:
names=='Will'

array([False, False,  True, False,  True, False, False])

In [8]:
data[names=='Will']

array([[ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843]])

<b>有兩個陣列分別為 x 與 x_sub，試著將 x_sub 的 [0,0] 改為 99，查看 x 陣列是否有改變?</b>

In [9]:
np.random.seed(0)
x = np.random.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [10]:
x_sub = x[:2, :2]
x_sub

array([[5, 0],
       [7, 9]])

In [11]:
x_sub[0, 0] = 99
x

array([[99,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

<b>請取出如下圖示的值
<details>
    <img src='./img/array_slice.png'>
</details>

In [13]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [15]:
orange_arr = arr[0,3:5];orange_arr

array([3, 4])

In [16]:
red_arr = arr[:,2];red_arr

array([ 2, 12, 22, 32, 42, 52])

In [17]:
green_arr = arr[2::2,::2];green_arr

array([[20, 22, 24],
       [40, 42, 44]])

In [18]:
lime_arr = arr[4:,4:];lime_arr

array([[44, 45],
       [54, 55]])

## Mod05 Lab

<b>使用 NumPy 版的三元運算子 x if c else y，試著將兩個陣列相同位置的元素較大者取出</b>

In [20]:
xarr = np.array([1.1, 3.2, 1.3, 1.4, 5.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [21]:
cond = xarr>yarr
result = np.where(cond, xarr, yarr)
result

array([2.1, 3.2, 2.3, 2.4, 5.5])

<b>有一個二維陣列 data，試著:
* 求 data 的平均值
* 求每一列的平均值
* 求每一行的平均值
</b>

In [22]:
data = np.arange(6).reshape((3,2))
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
np.mean(data)

2.5

In [25]:
np.mean(data, axis=1)

array([0.5, 2.5, 4.5])

In [24]:
np.mean(data, axis=0)

array([2., 3.])

## Mod06 Lab

<b>有一個陣列 arr，試著運算累計乘積:
* element-wise
* row-wise
* column-wise
</b>

In [ ]:
rand = np.random.RandomState(20)
arr = rand.randint(1, 11, size=(5,4))
arr

In [ ]:
arr.cumprod()

In [ ]:
arr.cumprod(axis=0)

In [ ]:
arr.cumprod(axis=1)

<b>有一個陣列 x，試著計算:
* 計算有多少值小於 6
* 檢查每列有多少小於 6 的值
</b>

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

In [ ]:
# how many data < 6
np.count_nonzero(x < 6)

In [ ]:
np.sum(x < 6)

In [ ]:
np.sum(x < 6, axis=1)

## Mod07 Lab

### ``Series`` as specialized dictionary
<b>有一個 Dictionary 如下，透過該 Dictionary 建立一個名為 sser 的 Series</b>

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
sser = pd.Series(sdata)
sser

<b>試著取得 sser 以下的資料:
* 'Texas' 的資料
* 'Texas' 到 'Utah' 的資料
* sser 的資料型態
</b>

In [ ]:
sdata['Texas']

In [ ]:
sser['Texas']

In [ ]:
sser['Texas':'Utah']

In [ ]:
sser.dtypes  # sser.dtype

<b>有兩個 Index 如下，試著取得這兩個 Index 不同的資料</b>    

In [ ]:
indX = pd.Index(['a', 'c', 'e', 'g', 'i'])
indY = pd.Index(['b', 'c', 'e', 'g', 'k'])

In [ ]:
indX ^ indY

## Mod08 Lab

<b>有一個 Dictionary 如下，透過該 Dictionary 建立一個 DataFrame，並顯示 columns 屬性</b>

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [ ]:
df = pd.DataFrame(data)
df

In [ ]:
df.columns

<b>匯入 data/tips.csv 的檔案到 DataFrame，顯示 DataFrame 前 10 筆資料，並顯示 dtypes 屬性</b>

In [ ]:
df = pd.read_csv('data/tips.csv')

In [ ]:
# View the first ten rows
df.head(10)

In [ ]:
df.dtypes

## Mod09 Lab

<b>有一個 Series ser，取得如下的資料:
* 透過 index 方式取得 13 這份資料
* 透過 slice 方式取得 36、13、35、17 四份資料
</b>

In [ ]:
np.random.seed(41)
ser = pd.Series(np.random.randint(1,50,size=7), index=list('abcdefg'))
ser

In [ ]:
# index
ser['c'] 

In [ ]:
# slice
ser['b':'e']

<b>有一個 Series data，取得如下的資料:
- 透過 loc與iloc 方式取得 'b' 這份資料
- 透過 loc與iloc 方式取得 'a', 'b', 'c' </b>

In [ ]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

In [ ]:
print(data.loc[3])
print(data.iloc[1])

In [ ]:
print(data.loc[1:5])
print(data.iloc[0:3])

## Mod10 Lab

<b>有一個 DataFrame df，取得如下的資料:
* 'two' 整欄的資料
* 'three' 與 'one' 這兩欄的資料
</b>

In [ ]:
np.random.seed(51)
df = pd.DataFrame(np.random.randint(11,70,size=20).reshape((4, 5)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four', 'five'])
df

In [ ]:
df['two']

In [ ]:
df[['three', 'one']]

<b>透過 loc 以及 iloc 取得 'three' 與 'one' 這兩欄的 'Ohio' 與 'Utah' 的資料</b>

In [ ]:
df.loc['Ohio':'Utah':2,'three':'one':-2]

In [ ]:
df.iloc[::2,2::-2]

<b>透過 at 以及 iat 取得 'Utah' 的 'three' 的資料</b>

In [ ]:
df.at['Utah','three']

In [ ]:
df.iat[2,2]

## Mod11 Lab

<b>有兩個 Series 如下，求兩個 Series 的和，遇到 NaN 以零代替</b>

In [ ]:
s1 = pd.Series([8.6, -3.2, 6.1, 2.4], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-4.2, 7.3, -2.7, 5, 1.8],
               index=['a', 'c', 'e', 'f', 'g'])

In [ ]:
s1

In [ ]:
s2

In [ ]:
s1 + s2

In [ ]:
s1.add(s2,fill_value=0)

<b>有兩個 DataFrame 如下，求兩個 DataFrame 的乘積，遇到 NaN 以 1 代替</b>

In [ ]:
np.random.seed(61)
df1 = pd.DataFrame(np.random.randint(10,size=12).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.random.randint(20,size=20).reshape((4, 5)),
                   columns=list('abcde'))

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1 * df2

In [ ]:
df1.multiply(df2,fill_value=1)

## Mod12 Lab

<b>有一個 DataFrame df 如下，試著正確的運算 df - df['Z'] 的結果</b>

operate column-wise by specifying the ``axis`` keyword:

In [ ]:
np.random.seed(62)
A = np.random.randint(10, size=(3, 4))

df = pd.DataFrame(A, columns=list('WXYZ'))
df

In [ ]:
df['Z']

In [ ]:
df - df['Z']

In [ ]:
df.subtract(df['Z'], axis=0)

In [ ]:
df.subtract(df['Z'], axis=1)
#df.subtract(df['R'])

## Mod13 Lab

<b>有一個 DataFrame df，試著計算空值個數有幾個?</b>

In [ ]:
arr = np.array([[ 8.,  2., 17., 20., 10.],
       [ 4., np.nan,  3., np.nan,  2.],
       [24., 26., 14., 23., 21.],
       [ 7., 29.,  3., 19., 25.],
       [14., 24., np.nan, 21., 10.],
       [np.nan, np.nan, 20., 26., np.nan]])

df = pd.DataFrame(arr, columns=['one', 'two', 'three', 'four', 'five'])
df

In [ ]:
df.values

In [ ]:
np.sum(df.isnull().values)

<b>試著將有空值的列拋棄</b>

In [ ]:
df.dropna()

<b>試著將空值超過一個以上的列拋棄</b>

In [ ]:
df.dropna(thresh=4)

## Mod14 Lab

<b>有一個 DataFrame df，試著計算整列重複的資料有幾個?</b>

In [ ]:
df = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
df

In [ ]:
df.duplicated()

In [ ]:
np.sum(df.duplicated())

<b>計算 'k1' 欄有幾個重複的資料</b>

In [ ]:
df.duplicated(subset=['k1'])

In [ ]:
np.sum(df.duplicated(subset=['k1']))

<b>試著將整列重複的拋棄，只留第一筆重複值</b>

In [ ]:
df.drop_duplicates()

## Mod15 Lab

<b>延續 planets 資料集，試著將所有的 'method' 偵測到的行星距離(ditance) 最大(max) 與最小(min) 的資料顯示出來</b>

In [ ]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

In [ ]:
planets.groupby('method')['distance'].agg(['min','max'])

<b>如果有空值，用 0 取代</b>

In [ ]:
planets.groupby('method')['distance'].agg(['min','max']).fillna(0)

## Mod16 Lab

<b>有兩個 DataFrame left 與 right，試著用預設的方式將兩個 DataFrame 合併(merge)</b>

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K4'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K5'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
left

In [ ]:
right

In [ ]:
pd.merge(left, right)

<b>使用 inner join 合併，與預設合併有何不同?</b>

In [ ]:
pd.merge(left, right, on='key', how='inner')

<b>使用 left join 合併，與預設合併有何不同?</b>

In [ ]:
pd.merge(left, right, on='key', how='left')

<b>使用 right join 合併，與預設合併有何不同?</b>

In [ ]:
pd.merge(left, right, on='key', how='right')

## Mod17 Lab

<b>有一個 DataFrame 如下</b>

In [ ]:
np.random.seed(70)
data = pd.DataFrame(np.random.randint(50, size=(6, 4)),
        index=['one', 'two', 'three', 'four', 'five', 'six'],
        columns=pd.Index(['A', 'B', 'C', 'D'], name='Genus'))
data

<b>利用 'A'、'C' 兩欄的資料繪製線型圖</b>

In [ ]:
ax = plt.gca()
data['A'].plot.line(ax=ax)
data['C'].plot.line(ax=ax)
plt.show();

<b>利用 'B'、'C'、'D' 三欄的資料做水平直條圖</b>

In [ ]:
data.iloc[:,1:].plot.barh();

<b>使用 'C' 欄資料建立圓餅圖，不要顯示 Y 軸標題，顯示圖表標題 "C data"，顯示各區塊的百分比</b>

In [ ]:
data['C'].plot.pie(autopct='%.2f%%')
plt.ylabel('')
plt.title('C data');

## Mod18 Lab

<b>有一個 DataFrame 如下</b>

In [ ]:
np.random.seed(11)
data = pd.DataFrame(np.random.randint(1,40, size=(6, 4)),
        index=['one', 'two', 'three', 'four', 'five', 'six'],
        columns=pd.Index(['A', 'B', 'C', 'D'], name='Genus'))
data

<b>利用 'D'欄的資料繪製直方圖，將 'bins' 設定為 5</b>

In [ ]:
data['D'].plot.hist(bins=5);

<b>利用 'A'、'B' 兩欄的資料繪製散佈圖，標記點形狀改為菱形，並將標記點大小加大</b>

In [ ]:
plt.plot(data['A'], data['B'], 'D', markersize=5);

In [ ]:
data.plot.scatter(x='A', y='B', s=30, marker='D');

<b>使用 data 資料建立區域圖，將圖例置於右上角，並以兩欄式顯示圖例</b>

In [ ]:
ax = data.plot.area()
ax.legend(loc='upper right', ncol=2);