# Mod03 Create NumPy Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.18.5'

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [3]:
ar1 = np.array([0,1,2,3]) # 1 dimensional array

In [4]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [5]:
ar1

array([0, 1, 2, 3])

In [6]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [7]:
# shape
ar2.shape

(2, 3)

In [8]:
# ndim
ar2.ndim

2

In [9]:
# dtype
ar2.dtype

dtype('int64')

## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [10]:
#ar3=np.arange(12); ar3
ar3=np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
# start, end (exclusive)
#ar4=np.arange(3,10,3); ar4
ar4=np.arange(3,10,3)
ar4

array([3, 6, 9])

In [12]:
ar5=np.arange(5,10)
ar5  

array([5, 6, 7, 8, 9])

In [13]:
type(ar5)  

numpy.ndarray

## NumPy datatypes
Specify the type of contents of a numeric array by using the dtype parameter

In [14]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype='float');
ar

array([ 2., -1.,  6.,  3.])

In [15]:
ar.dtype

dtype('float64')

In [16]:
ar=np.array([2,4,6,8]); ar.dtype

dtype('int64')

In [17]:
ar=np.array([2.,4,6,8]); ar.dtype

dtype('float64')

In [18]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); sar.dtype

dtype('<U9')

In [19]:
bar=np.array([True, False, True]); bar.dtype

dtype('bool')

In [20]:
f_ar = np.array([3,-2,8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [21]:
f_ar.astype(int)

array([ 3, -2,  8])

## NumPy array creation via numpy.linspace
ndarray.linspace generates linear evenly spaced elements between the start and the end

In [22]:
# args - start element,end element, number of elements
#ar6=np.linspace(0,2.0/3,4); ar5
ar6=np.linspace(0,2.0/3,4)
ar6

array([0.        , 0.22222222, 0.44444444, 0.66666667])

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

### numpy.ones

In [23]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.zeros

In [24]:
# Produce 4x2 array of zeros.
ar8=np.zeros((4,2)); ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.eye

In [25]:
# Produces identity matrix
ar9 = np.eye(3); ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.empty

In [26]:
ar13=np.empty((3,2)); ar13

array([[2.4673401e-316, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])

### numpy.random.rand

In [27]:
# Using the rand, randn functions
# rand(m) produces an array of the given shape 
# with uniformly distributed random numbers over [0,1)
np.random.seed(200) # Set seed
ar11=np.random.rand(3); ar11

array([0.94763226, 0.22654742, 0.59442014])

In [28]:
# randn(m) produces m normally distributed (Gaussian) random numbers
ar12=np.random.randn(5); ar12

array([ 1.4983231 , -0.40666493, -0.09376948,  0.87472083,  0.83141749])

In [29]:
ar13=np.random.randint(100,size=(7,)); ar13

array([54, 77, 16, 70, 35, 31, 32])

## Lab

<b> 利用 arange() 建立一個 array([11, 14, 17, 20]) 的陣列 <b>

<b>建立一個陣列如下，並列出陣列形狀與維度
```
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
```
</b>
