# Mod03 Create NumPy Array

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.__version__

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [ ]:
ar1 = np.array([0,1,2,3]) # 1 dimensional array

In [ ]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [ ]:
ar1

In [ ]:
ar2

In [ ]:
# shape
ar2.shape

In [ ]:
# ndim
ar2.ndim

In [ ]:
# dtype
ar2.dtype

## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [ ]:
#ar3=np.arange(12); ar3
ar3=np.arange(12)
ar3

In [ ]:
# start, end (exclusive)
#ar4=np.arange(3,10,3); ar4
ar4=np.arange(3,10,3)
ar4

In [ ]:
ar5=np.arange(5,10)
ar5  

In [ ]:
type(ar5)  

## NumPy datatypes
Specify the type of contents of a numeric array by using the dtype parameter

In [ ]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype='float');
ar

In [ ]:
ar.dtype

In [ ]:
ar=np.array([2,4,6,8]); ar.dtype

In [ ]:
ar=np.array([2.,4,6,8]); ar.dtype

In [ ]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); sar.dtype

In [ ]:
bar=np.array([True, False, True]); bar.dtype

In [ ]:
f_ar = np.array([3,-2,8.18])
f_ar

In [ ]:
f_ar.astype(int)

## NumPy array creation via numpy.linspace
ndarray.linspace generates linear evenly spaced elements between the start and the end

In [ ]:
# args - start element,end element, number of elements
#ar6=np.linspace(0,2.0/3,4); ar5
ar6=np.linspace(0,2.0/3,4)
ar6

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

### numpy.ones

In [ ]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

### numpy.zeros

In [ ]:
# Produce 4x2 array of zeros.
ar8=np.zeros((4,2)); ar8

### numpy.eye

In [ ]:
# Produces identity matrix
ar9 = np.eye(3); ar9

### numpy.empty

In [ ]:
ar13=np.empty((3,2)); ar13

### numpy.random.rand

In [15]:
# Using the rand, randn functions
# rand(m) produces an array of the given shape 
# with uniformly distributed random numbers over [0,1)
np.random.seed(200) # Set seed
ar11=np.random.rand(3); ar11

array([0.94763226, 0.22654742, 0.59442014])

In [16]:
# randn(m) produces m normally distributed (Gaussian) random numbers
ar12=np.random.randn(5); ar12

array([ 1.4983231 , -0.40666493, -0.09376948,  0.87472083,  0.83141749])

In [21]:
ar13=np.random.randint(100,size=(7,)); ar13

array([85,  0,  3, 55, 95, 56,  3])

## Lab

<b> 利用 arange() 建立一個 array([11, 14, 17, 20]) 的陣列 <b>

<b>建立一個陣列如下，並列出陣列形狀與維度
```
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
```
</b>


[[1. 2. 1. 2.]
 [3. 4. 3. 4.]]
