# Mod06 NumPy Advanced Operations

# Operations

## Advanced Operations

In [2]:
import numpy as np
import pandas as pd

## Statistical operators

In [3]:
arr=np.array([9, 4, 1, 2, 9])
arr.mean()

5.0

In [4]:
arr.std()

3.40587727318528

In [5]:
np.random.seed(10)
ar=np.random.randint(0,10, size=(4,5)); ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [6]:
ar.mean()

4.45

In [7]:
ar.mean(axis=0)

array([5.25, 4.25, 5.  , 3.5 , 4.25])

In [8]:
ar.mean(axis=1)

array([4.6, 3.6, 4.2, 5.4])

In [9]:
ar.var(axis=1) #across columns

array([14.64, 16.24,  7.36,  7.04])

In [10]:
ar.var(axis=0) #across rows

array([12.6875,  4.1875, 11.    , 10.75  , 18.1875])

In [11]:
ar.cumsum()

array([ 9, 13, 13, 14, 23, 23, 24, 32, 41, 41, 49, 55, 59, 62, 62, 66, 72,
       80, 81, 89])

In [12]:
ar.cumsum(axis=1)

array([[ 9, 13, 13, 14, 23],
       [ 0,  1,  9, 18, 18],
       [ 8, 14, 18, 21, 21],
       [ 4, 10, 18, 19, 27]])

In [13]:
ar.cumprod()

array([ 9, 36,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0])

In [14]:
ar.cumprod(axis=0)

array([[  9,   4,   0,   1,   9],
       [  0,   4,   0,   9,   0],
       [  0,  24,   0,  27,   0],
       [  0, 144,   0,  27,   0]])

## Reduction Logical operators

In [12]:
np.random.seed(100)
ar=np.random.randint(1,10, size=(4,4)); ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [13]:
ar=np.array([9, 9, 4, 8])
np.any((ar%7)==0)

False

In [14]:
np.all(ar<11)

True

#### 計算布林陣列內有多少 “True” 的值

In [ ]:
np.sum(ar < 6)

## Broadcasting

In [17]:
ar=np.array([[1., 1.],[1., 1.]])
ar2=np.array([2, 3])

In [18]:
ar+ar2

array([[3., 4.],
       [3., 4.]])

<b>Broadcasting works across dimensions</b>

In [19]:
ar=np.array([[23,24,25]]); ar

array([[23, 24, 25]])

In [20]:
ar.T

array([[23],
       [24],
       [25]])

In [21]:
ar.T+ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])

<b>Row expansion</b>

In [15]:
ar1 = np.array([[0, 0, 0],
                [1, 1, 1],
                [2, 2, 2],
                [3, 3, 3]])
ar1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [17]:
ar=np.random.randint(0,10, size=(4,5)); 

In [23]:
ar2=np.array([1,2,3])
ar2

array([1, 2, 3])

In [24]:
ar1+ar2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

<b>Column expansion</b>

In [25]:
ar1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [26]:
ar2=np.array([1,2,3,4])
ar3=ar2.reshape((4,1))
ar3

array([[1],
       [2],
       [3],
       [4]])

In [27]:
ar1+ar3

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

## Lab

<b>有一個陣列 arr，試著運算累計乘積:
* element-wise
* row-wise
* column-wise
</b>

In [ ]:
rand = np.random.RandomState(20)
arr = rand.randint(1, 11, size=(5,4))
arr

<b>有一個陣列 x，試著計算:
* 計算有多少值小於 6
* 檢查每列有多少小於 6 的值
</b>

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

# 補充

<details>
    <summary><b>axis 與 shape</b></summary>
    <img src='./img/axis_shape.png'>
</details>

In [4]:
x = np.arange(24).reshape(2,3,4)
print(f'x.shape:{x.shape}')
print(x)

x.shape:(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


<b>另外，也可以由內往外數，最內部的第一個中括號就是axis=-1，越外面就越小(負得越多)。</b>

In [9]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(C,end='\n-------------\n')
print(np.sum(C,axis=-3),end='\n-------------\n')
print(np.sum(C,axis=0),end='\n-------------\n')
print(np.sum(C,axis=-2),end='\n-------------\n')
print(np.sum(C,axis=1),end='\n-------------\n')
print(np.sum(C,axis=-1),end='\n-------------\n')
print(np.sum(C,axis=2),end='\n-------------\n')


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-------------
[[ 8 10 12]
 [14 16 18]]
-------------
[[ 8 10 12]
 [14 16 18]]
-------------
[[ 5  7  9]
 [17 19 21]]
-------------
[[ 5  7  9]
 [17 19 21]]
-------------
[[ 6 15]
 [24 33]]
-------------
[[ 6 15]
 [24 33]]
-------------


<b>參與運算的所有陣列必須符合以下規則才能做broadcasting，所有矩陣的shape由[axis＝-1開始]對齊去比較彼此間的數值，比較結果必須符合以下兩種規則其中之一：</b><br>
    1. 兩個陣列的相同axis的數值為同一個值<br>
    2. 如果兩個陣列的相同axis的數值為不同值，則其中一個數值必定是0或1

In [10]:
# 可以broadcast的陣列
ar1=np.random.randint(0,100,size=(8,7,1,5,9,1))
ar2=np.random.randint(0,100,size=(8,1,5,5,1,6)) 
a = ar1*ar2
a.shape

(8, 7, 5, 5, 9, 6)

In [ ]:
# 可以broadcast的陣列
ar1=np.random.randint(0,100,size=(3,5)) 
ar2=np.random.randint(0,100,size=(6,2,1,3,5))
a = ar1*ar2
a.shape

In [ ]:
# 不能broadcast的陣列
ar1=np.random.randint(0,100,size=(3,9)) 
ar2=np.random.randint(0,100,size=(6,2,1,3,5))
ar1*ar2